require('./read')
  .then(require('./remove-non-team-comments'))
  .then(require('./add-language-to-comment'))
  .then(require('./add-pr-to-comment'))
  .then(require('./build-team'))
  .then(require('./add-pr-to-user'))
  .then(require('./add-comments-to-users'))
  .then(require('./visualize/comment-links'))
  .then(require('./visualize/language-links'))
  .then(require('./visualize/office-links'))
  .then(require('./visualize/common-words'))
  .then(require('./visualize/comments-over-time'))
  .then(require('./visualize/user-stats'))
  .then(require('./visualize/user-awards'))
	.catch (error)-> console.log error.stack
